### PR TITLE
Copy all files from curriculum branch

### PR DESCRIPTION
**Pull request by alexgriff**
Update to copy all files from curriculum branch over to other branches

### CODE REVIEW

**Comment by lmcm18** [comment]
@alexgriff @LoreDirick @mas16 
👍 works for me.

**Review by lmcm18 — COMMENTED** [review]
Works for me. 👍 @alexgriff @mas16 @LoreDirick

**Comment by mas16** [comment]
also works for me 👍

**Review by mas16 — COMMENTED** [review]
looks great

**Pull request merged**
